# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 781, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.degree_label = QtWidgets.QLabel(self.centralwidget)
        self.degree_label.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.degree_label.setObjectName("degree_label")
        self.degree = QtWidgets.QSpinBox(self.centralwidget)
        self.degree.setGeometry(QtCore.QRect(110, 40, 42, 22))
        self.degree.setMinimum(1)
        self.degree.setMaximum(5)
        self.degree.setObjectName("degree")
        self.ground = QtWidgets.QCheckBox(self.centralwidget)
        self.ground.setGeometry(QtCore.QRect(170, 40, 81, 16))
        self.ground.setObjectName("ground")
        self.grained = QtWidgets.QCheckBox(self.centralwidget)
        self.grained.setGeometry(QtCore.QRect(240, 40, 82, 17))
        self.grained.setObjectName("grained")
        self.price_label = QtWidgets.QLabel(self.centralwidget)
        self.price_label.setGeometry(QtCore.QRect(320, 43, 47, 16))
        self.price_label.setObjectName("price_label")
        self.price = QtWidgets.QLineEdit(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(360, 40, 113, 21))
        self.price.setObjectName("price")
        self.package_size = QtWidgets.QLineEdit(self.centralwidget)
        self.package_size.setGeometry(QtCore.QRect(590, 40, 113, 21))
        self.package_size.setObjectName("package_size")
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        self.size_label.setGeometry(QtCore.QRect(490, 43, 91, 16))
        self.size_label.setObjectName("size_label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 40, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(10, 10, 381, 23))
        self.addButton.setObjectName("addButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(420, 10, 371, 23))
        self.editButton.setObjectName("editButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.degree_label.setText(_translate("MainWindow", "Степень обжарки"))
        self.ground.setText(_translate("MainWindow", "молотый"))
        self.grained.setText(_translate("MainWindow", "в зёрнах"))
        self.price_label.setText(_translate("MainWindow", "Цена"))
        self.size_label.setText(_translate("MainWindow", "Размер упаковки"))
        self.pushButton.setText(_translate("MainWindow", "Искать"))
        self.addButton.setText(_translate("MainWindow", "Добавить запись"))
        self.editButton.setText(_translate("MainWindow", "Редактировать запись"))
